# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"0\n\x0eSearchResponse\x12\x1e\n\x07results\x18\x01 \x03(\x0b\x32\r.SearchResult\".\n\x0cSearchResult\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07snippet\x18\x02 \x01(\t2<\n\rSearchService\x12+\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHREQUEST']._serialized_start=16
  _globals['_SEARCHREQUEST']._serialized_end=46
  _globals['_SEARCHRESPONSE']._serialized_start=48
  _globals['_SEARCHRESPONSE']._serialized_end=96
  _globals['_SEARCHRESULT']._serialized_start=98
  _globals['_SEARCHRESULT']._serialized_end=144
  _globals['_SEARCHSERVICE']._serialized_start=146
  _globals['_SEARCHSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
